name: 🧹 Clean-up merged release-please branch

on:
  push:
    branches: [main]

jobs:
  delete-release-please-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to delete refs
    steps:
      - name: Delete branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = 'release-please--branches--main';
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchName}`
              });
              console.log(`✅ Deleted branch: ${branchName}`);
            } catch (err) {
              console.log(`ℹ️  Branch ${branchName} already gone or protected: ${err.message}`);
            }
