name: Publish VaultNote (Linux)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-tauri:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf build-essential curl libssl-dev libgtk-3-dev
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'  # Matches your previous setup
          cache: 'npm'  # Cache npm dependencies
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'x86_64-unknown-linux-gnu'
      - name: Cache Rust artifacts
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Install frontend dependencies
        run: npm install
      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: vaultnote-v__VERSION__  # e.g., vaultnote-v0.1.0
          releaseName: 'VaultNote v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: '--target x86_64-unknown-linux-gnu'
      - name: Verify artifacts
        run: ls -R src-tauri/target/release/bundle
