name: Publish VaultNote (Linux)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-tauri:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf build-essential curl libssl-dev libgtk-3-dev rpm
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'x86_64-unknown-linux-gnu'
      - name: Cache Rust artifacts
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Clear caches to ensure updated config
        run: |
          rm -rf src-tauri/target
          rm -rf node_modules
          rm -rf .svelte-kit
      - name: Install frontend dependencies
        run: bun install
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main
          tag_prefix: vaultnote-v
      - name: Update tauri.conf.json version
        run: |
          bunx --bun json -I -f src-tauri/tauri.conf.json -e "this.version='${{ steps.bump_version.outputs.new_tag }}'.replace('vaultnote-v', '')"
      - name: Commit version changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add package.json src-tauri/tauri.conf.json
          git commit -m "ci: version bump to ${{ steps.bump_version.outputs.new_tag }}"
          git push
      - name: Create bundle directories
        run: |
          mkdir -p src-tauri/target/release/bundle/deb
          mkdir -p src-tauri/target/release/bundle/appimage
          mkdir -p src-tauri/target/release/bundle/rpm
      - name: Build and release
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.bump_version.outputs.new_tag }}
          releaseName: VaultNote v${{ steps.bump_version.outputs.new_tag }}
          releaseBody: See the assets to download this version and install.
          releaseDraft: false
          prerelease: false
          appVersion: ${{ steps.bump_version.outputs.new_tag }}
          args: --target x86_64-unknown-linux-gnu --bundles deb,appimage,rpm
          beforeBuildCommand: bun run vite build
      - name: Move artifacts to bundle directories
        run: |
          find src-tauri/target -name "vaultnote_*.deb" -exec mv {} src-tauri/target/release/bundle/deb/ \;
          find src-tauri/target -name "vaultnote_*.AppImage" -exec mv {} src-tauri/target/release/bundle/appimage/ \;
          find src-tauri/target -name "vaultnote-*.rpm" -exec mv {} src-tauri/target/release/bundle/rpm/ \;
      - name: Verify artifacts
        run: ls -R src-tauri/target/release/bundle
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vaultnote-ubuntu
          path: src-tauri/target/release/bundle/**
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          name: VaultNote v${{ steps.bump_version.outputs.new_tag }}
          body: See the assets to download this version and install.
          draft: false
          prerelease: false
          files: |
            src-tauri/target/release/bundle/deb/*
            src-tauri/target/release/bundle/appimage/*
            src-tauri/target/release/bundle/rpm/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
