name: Publish VaultNote (Linux)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-tauri:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf build-essential curl libssl-dev libgtk-3-dev
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'x86_64-unknown-linux-gnu'
      - name: Cache Rust artifacts
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Install frontend dependencies
        run: bun install
      - name: Create bundle directory
        run: mkdir -p src-tauri/target/release/bundle/deb
      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: vaultnote-v__VERSION__
          releaseName: 'VaultNote v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: '--target x86_64-unknown-linux-gnu'
          beforeBuildCommand: 'bun run vite build'
      - name: Move artifacts to bundle directory
        run: |
          find src-tauri/target -name "vaultnote_*.deb" -exec mv {} src-tauri/target/release/bundle/deb/ \;
      - name: Verify artifacts
        run: ls -R src-tauri/target/release/bundle
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vaultnote-ubuntu
          path: src-tauri/target/release/bundle/**
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: vaultnote-v__VERSION__
          name: VaultNote v__VERSION__
          body: See the assets to download this version and install.
          draft: true
          prerelease: false
          files: src-tauri/target/release/bundle/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
