name: Publish VaultNote (Linux and Android)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (patch, minor)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor

permissions:
  contents: write

jobs:
  publish-tauri-linux:
    runs-on: ubuntu-22.04
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Required to retrieve full commit history
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf build-essential curl libssl-dev libgtk-3-dev rpm
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'x86_64-unknown-linux-gnu'
      - name: Cache Rust artifacts
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Install frontend dependencies
        run: bun install
      - name: Install json for version update
        run: bun add -g json
      - name: Bump version
        id: bump_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.version_bump || 'patch' }}
          release_branches: main
          tag_prefix: vaultnote-v
          branch_history: compare # Use compare for efficient commit history checking
      - name: Update tauri.conf.json version
        run: |
          bunx --bun json -I -f src-tauri/tauri.conf.json -e "this.version='${{ steps.bump_version.outputs.new_tag }}'.replace('vaultnote-v', '')"
      - name: Commit version changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add src-tauri/tauri.conf.json
          git commit -m "ci: version bump to ${{ steps.bu
mp_version.outputs.new_tag }} [skip ci]" # Add [skip ci] to prevent infinite loops
          git push
      - name: Create bundle directories
        run: |
          mkdir -p src-tauri/target/release/bundle/deb
          mkdir -p src-tauri/target/release/bundle/appimage
          mkdir -p src-tauri/target/release/bundle/rpm
      - name: Build and release
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.bump_version.outputs.new_tag }}
          releaseName: VaultNote v${{ steps.bump_version.outputs.new_tag }}
          releaseBody: See the assets to download this version and install.
          releaseDraft: false
          prerelease: false
          appVersion: ${{ steps.bump_version.outputs.new_tag }}
          args: --target x86_64-unknown-linux-gnu --bundles deb,appimage,rpm
          beforeBuildCommand: bun run vite build
      - name: Move artifacts to bundle directories
        run: |
          find src-tauri/target -name "vaultnote_*.deb" -exec mv {} src-tauri/target/release/bundle/deb/ \;
          find src-tauri/target -name "vaultnote_*.AppImage" -exec mv {} src-tauri/target/release/bundle/appimage/ \;
          find src-tauri/target -name "vaultnote-*.rpm" -exec mv {} src-tauri/target/release/bundle/rpm/ \;
      - name: Verify artifacts
        run: ls -R src-tauri/target/release/bundle
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vaultnote-ubuntu
          path: src-tauri/target/release/bundle/**
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.new_tag }}
          name: VaultNote v${{ steps.bump_version.outputs.new_tag }}
          body: See the assets to download this version and install.
          draft: false
          prerelease: false
          files: |
            src-tauri/target/release/bundle/deb/*
            src-tauri/target/release/bundle/appimage/*
            src-tauri/target/release/bundle/rpm/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-tauri-android:
    runs-on: ubuntu-22.04
    needs: publish-tauri-linux
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Required for commit history
      - name: Install Android dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk clang cmake ninja-build
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android'
      - name: Cache Rust artifacts
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
      - name: Setup Android SDK/NDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '34'
          ndk-version: '26.1.10909125'
      - name: Install frontend dependencies
        run: bun install
      - name: Install json for version update
        run: bun add -g json
      - name: Update tauri.conf.json version
        run: |
          bunx --bun json -I -f src-tauri/tauri.conf.json -e "this.version='${{ needs.publish-tauri-linux.outputs.new_tag }}'.replace('vaultnote-v', '')"
      - name: Create bundle directories
        run: |
          mkdir -p src-tauri/target/release/bundle/apk
          mkdir -p src-tauri/target/release/bundle/aab
      - name: Build and release
        uses: tauri-apps/tauri-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.1.10909125
        with:
          tagName: ${{ needs.publish-tauri-linux.outputs.new_tag }}
          releaseName: VaultNote v${{ needs.publish-tauri-linux.outputs.new_tag }}
          releaseBody: See the assets to download this version and install.
          releaseDraft: false
          prerelease: false
          appVersion: ${{ needs.publish-tauri-linux.outputs.new_tag }}
          args: --target aarch64-linux-android --bundles apk,aab
          beforeBuildCommand: bun run vite build
      - name: Move artifacts to bundle directories
        run: |
          find src-tauri/target -name "vaultnote_*.apk" -exec mv {} src-tauri/target/release/bundle/apk/ \;
          find src-tauri/target -name "vaultnote_*.aab" -exec mv {} src-tauri/target/release/bundle/aab/ \;
      - name: Verify artifacts
        run: ls -R src-tauri/target/release/bundle
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vaultnote-android
          path: src-tauri/target/release/bundle/**
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.publish-tauri-linux.outputs.new_tag }}
          name: VaultNote v${{ needs.publish-tauri-linux.outputs.new_tag }}
          body: See the assets to download this version and install.
          draft: false
          prerelease: false
          files: |
            src-tauri/target/release/bundle/apk/*
            src-tauri/target/release/bundle/aab/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
