name: CI / CD – VaultNote

on:
  push:
    branches:
      - main # runs CI
    tags:
      - "v*" # runs release

  # Optional manual version bump if you want an explicit button
  workflow_dispatch:
    inputs:
      bump:
        description: "Manual version bump type"
        required: true
        default: patch
        type: choice
        options: [patch, minor, major]

permissions:
  contents: write

jobs:
  # ----------  CI build (every push to main)  ----------
  ci:
    name: CI build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
          - platform: macos-latest
          - platform: windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2 # Bun runtime
      - uses: dtolnay/rust-toolchain@stable # Rust toolchain
      - uses: swatinem/rust-cache@v2
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        if: runner.os == 'Linux'
      - run: bun install
      - run: bun run build
      - run: bun run tauri build

  # ----------  Release build (on vX.Y.Z tag push)  ----------
  release:
    name: Create release
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            args: ""
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
          - platform: windows-latest
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - uses: swatinem/rust-cache@v2
      - run: bun install
      - name: Patch tauri.conf.json version
        run: |
          TAG=${GITHUB_REF_NAME#v}
          npx json -I -f src-tauri/tauri.conf.json \
                 -e "this.version='$TAG'"
      - name: Build web assets
        env:
          NODE_ENV: production
        run: bun run build
      - name: Build & release via tauri-action
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "VaultNote v${{ github.ref_name }}"
          releaseBody: |
            See the assets to download this version and install manually,
            or update via the built-in updater.
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

  # ----------  Optional manual version bump workflow ----------
  version-bump:
    name: Manual version bump
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - name: "Bump version & push tag"
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.bump }}
          tag_prefix: "v"
      - name: "Update tauri.conf.json"
        run: |
          TAG=${{ env.NEW_TAG # set by the step above
          npx json -I -f src-tauri/tauri.conf.json \
                 -e "this.version='${TAG#v}'"
      - name: "Commit version bump"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src-tauri/tauri.conf.json
          git commit -m "chore(release): bump to $TAG"
          git push
